backend:
  name: github
  repo: cat-nation/cat-nation # <-- CHANGE TO YOUR EXACT GITHUB USERNAME AND REPOSITORY NAME
  branch: main # <-- Change to master if your repo branch name is master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "citizens"
    label: "Citizen List"
    folder: "citizens"
    create: true
    fields:
      - { label: "Citizen Name", name: "title", widget: "string" }
      - { label: "Role", name: "body", widget: "markdown" }
