backend:
  name: github
  repo: cat-nation/cat-nation
  branch: main

media_folder: "images/citizens"
public_folder: "/images/citizens"

collections:
  - name: "citizens"
    label: "Citizen Registry"
    folder: "data/citizens"
    create: true
    slug: "citizen-{{id}}"
    fields:
      - { label: "National ID Number", name: "id", widget: "string" }
      - { label: "Full Legal Name", name: "title", widget: "string" }
      - { label: "Date of Citizenship", name: "date", widget: "datetime" }
      - { label: "National Status/Role", name: "role", widget: "select", options: ["Citizen", "Ambassador", "Cabinet Minister", "Noble"] }
      - { label: "Biography & Records", name: "body", widget: "markdown" }
